/*
 * generated by Xtext 2.25.0
 */
package dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGreenhouseScopeProvider extends DelegatingScopeProvider {
}
