/**
 * generated by Xtext 2.25.0
 */
package dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GreenhouseUiModule extends AbstractGreenhouseUiModule {
  public GreenhouseUiModule(final AbstractUIPlugin plugin) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe type GreenhouseUiModule is already defined in GreenhouseUiModule.java.");
  }
}
