/*
 * generated by Xtext 2.25.0
 */
package dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GreenhouseStandaloneSetup extends GreenhouseStandaloneSetupGenerated {

	def static void doSetup() {
		new GreenhouseStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
