/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Controller</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.Controller#getName <em>Name</em>}</li>
 *   <li>{@link dsl.greenhouse.Controller#getType <em>Type</em>}</li>
 *   <li>{@link dsl.greenhouse.Controller#getHeartBeat <em>Heart Beat</em>}</li>
 * </ul>
 *
 * @see dsl.greenhouse.GreenhousePackage#getController()
 * @model
 * @generated
 */
public interface Controller extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dsl.greenhouse.GreenhousePackage#getController_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dsl.greenhouse.Controller#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(ControllerType)
   * @see dsl.greenhouse.GreenhousePackage#getController_Type()
   * @model containment="true"
   * @generated
   */
  ControllerType getType();

  /**
   * Sets the value of the '{@link dsl.greenhouse.Controller#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(ControllerType value);

  /**
   * Returns the value of the '<em><b>Heart Beat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Heart Beat</em>' containment reference.
   * @see #setHeartBeat(Heartbeat)
   * @see dsl.greenhouse.GreenhousePackage#getController_HeartBeat()
   * @model containment="true"
   * @generated
   */
  Heartbeat getHeartBeat();

  /**
   * Sets the value of the '{@link dsl.greenhouse.Controller#getHeartBeat <em>Heart Beat</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Heart Beat</em>' containment reference.
   * @see #getHeartBeat()
   * @generated
   */
  void setHeartBeat(Heartbeat value);

} // Controller
