/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Frequency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.Frequency#getFreq <em>Freq</em>}</li>
 *   <li>{@link dsl.greenhouse.Frequency#getUnit <em>Unit</em>}</li>
 * </ul>
 *
 * @see dsl.greenhouse.GreenhousePackage#getFrequency()
 * @model
 * @generated
 */
public interface Frequency extends EObject
{
  /**
   * Returns the value of the '<em><b>Freq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Freq</em>' containment reference.
   * @see #setFreq(Expression)
   * @see dsl.greenhouse.GreenhousePackage#getFrequency_Freq()
   * @model containment="true"
   * @generated
   */
  Expression getFreq();

  /**
   * Sets the value of the '{@link dsl.greenhouse.Frequency#getFreq <em>Freq</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Freq</em>' containment reference.
   * @see #getFreq()
   * @generated
   */
  void setFreq(Expression value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' attribute.
   * @see #setUnit(String)
   * @see dsl.greenhouse.GreenhousePackage#getFrequency_Unit()
   * @model
   * @generated
   */
  String getUnit();

  /**
   * Sets the value of the '{@link dsl.greenhouse.Frequency#getUnit <em>Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' attribute.
   * @see #getUnit()
   * @generated
   */
  void setUnit(String value);

} // Frequency
