/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dsl.greenhouse.GreenhouseFactory
 * @model kind="package"
 * @generated
 */
public interface GreenhousePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "greenhouse";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Greenhouse.dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "greenhouse";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GreenhousePackage eINSTANCE = dsl.greenhouse.impl.GreenhousePackageImpl.init();

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ModelImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Hardware Setup</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__HARDWARE_SETUP = 1;

  /**
   * The feature id for the '<em><b>Greenhouses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GREENHOUSES = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.HardwareSetupImpl <em>Hardware Setup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.HardwareSetupImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardwareSetup()
   * @generated
   */
  int HARDWARE_SETUP = 1;

  /**
   * The feature id for the '<em><b>Hardware</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE_SETUP__HARDWARE = 0;

  /**
   * The feature id for the '<em><b>Controllers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE_SETUP__CONTROLLERS = 1;

  /**
   * The number of structural features of the '<em>Hardware Setup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE_SETUP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.HardwareImpl <em>Hardware</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.HardwareImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardware()
   * @generated
   */
  int HARDWARE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE__NAME = 0;

  /**
   * The number of structural features of the '<em>Hardware</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingActuatorImpl <em>Setting Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingActuatorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingActuator()
   * @generated
   */
  int SETTING_ACTUATOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR__NAME = HARDWARE__NAME;

  /**
   * The feature id for the '<em><b>Setting Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR__SETTING_ACTION = HARDWARE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Setting Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR_FEATURE_COUNT = HARDWARE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingSensorImpl <em>Setting Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingSensorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingSensor()
   * @generated
   */
  int SETTING_SENSOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR__NAME = HARDWARE__NAME;

  /**
   * The feature id for the '<em><b>Reducer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR__REDUCER = HARDWARE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR__FREQUENCY = HARDWARE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Setting Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR_FEATURE_COUNT = HARDWARE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ControllerImpl <em>Controller</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ControllerImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getController()
   * @generated
   */
  int CONTROLLER = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__TYPE = 1;

  /**
   * The feature id for the '<em><b>Heart Beat</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER__HEART_BEAT = 2;

  /**
   * The number of structural features of the '<em>Controller</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.HeartbeatImpl <em>Heartbeat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.HeartbeatImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHeartbeat()
   * @generated
   */
  int HEARTBEAT = 6;

  /**
   * The feature id for the '<em><b>Freq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEARTBEAT__FREQ = 0;

  /**
   * The number of structural features of the '<em>Heartbeat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEARTBEAT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ControllerTypeImpl <em>Controller Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ControllerTypeImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getControllerType()
   * @generated
   */
  int CONTROLLER_TYPE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Controller Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROLLER_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ReducerImpl <em>Reducer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ReducerImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getReducer()
   * @generated
   */
  int REDUCER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDUCER__NAME = 0;

  /**
   * The number of structural features of the '<em>Reducer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REDUCER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.FrequencyImpl <em>Frequency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.FrequencyImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getFrequency()
   * @generated
   */
  int FREQUENCY = 9;

  /**
   * The feature id for the '<em><b>Freq</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREQUENCY__FREQ = 0;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREQUENCY__UNIT = 1;

  /**
   * The number of structural features of the '<em>Frequency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FREQUENCY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingActionImpl <em>Setting Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingActionImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingAction()
   * @generated
   */
  int SETTING_ACTION = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTION__NAME = 0;

  /**
   * The number of structural features of the '<em>Setting Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseImpl <em>Greenhouse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouse()
   * @generated
   */
  int GREENHOUSE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE__NAME = 0;

  /**
   * The feature id for the '<em><b>Row</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE__ROW = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE__ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Greenhouse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRow()
   * @generated
   */
  int ROW = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseElementImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseElement()
   * @generated
   */
  int GREENHOUSE_ELEMENT = 13;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowElementImpl <em>Row Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowElementImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowElement()
   * @generated
   */
  int ROW_ELEMENT = 14;

  /**
   * The number of structural features of the '<em>Row Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseActuatorImpl <em>Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseActuatorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseActuator()
   * @generated
   */
  int GREENHOUSE_ACTUATOR = 15;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__TYPE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__NAME = GREENHOUSE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Controller</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__CONTROLLER = GREENHOUSE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__ACTION = GREENHOUSE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Safe State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__SAFE_STATE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR_FEATURE_COUNT = GREENHOUSE_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowActuatorImpl <em>Row Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowActuatorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowActuator()
   * @generated
   */
  int ROW_ACTUATOR = 16;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__TYPE = ROW_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__NAME = ROW_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Controller</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__CONTROLLER = ROW_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__ACTION = ROW_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Safe State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__SAFE_STATE = ROW_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Row Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR_FEATURE_COUNT = ROW_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseSensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseSensorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseSensor()
   * @generated
   */
  int GREENHOUSE_SENSOR = 17;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__TYPE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__NAME = GREENHOUSE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Controller</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__CONTROLLER = GREENHOUSE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__VARIABLE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__STATES = GREENHOUSE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR_FEATURE_COUNT = GREENHOUSE_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowSensorImpl <em>Row Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowSensorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowSensor()
   * @generated
   */
  int ROW_SENSOR = 18;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__TYPE = ROW_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__NAME = ROW_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Controller</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__CONTROLLER = ROW_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__VARIABLE = ROW_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__STATES = ROW_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Row Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR_FEATURE_COUNT = ROW_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.StateImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getState()
   * @generated
   */
  int STATE = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__OP = 2;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__THRESHOLD = 3;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.VariableImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ActionImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getAction()
   * @generated
   */
  int ACTION = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__VALUE = 0;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__TRIGGER = 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.TriggerImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 22;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__NAME = 0;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowRuleSetImpl <em>Row Rule Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowRuleSetImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowRuleSet()
   * @generated
   */
  int ROW_RULE_SET = 23;

  /**
   * The feature id for the '<em><b>Actuator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__ACTUATOR = ROW_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__TRIGGER = ROW_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__SENSOR = ROW_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__STATE = ROW_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Row Rule Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET_FEATURE_COUNT = ROW_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseRuleSetImpl <em>Rule Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseRuleSetImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseRuleSet()
   * @generated
   */
  int GREENHOUSE_RULE_SET = 24;

  /**
   * The feature id for the '<em><b>Actuator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__ACTUATOR = GREENHOUSE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__TRIGGER = GREENHOUSE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__SENSOR = GREENHOUSE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__STATE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Rule Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET_FEATURE_COUNT = GREENHOUSE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ExpressionImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 25;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.PlusImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getPlus()
   * @generated
   */
  int PLUS = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.MinusImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getMinus()
   * @generated
   */
  int MINUS = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.MultImpl <em>Mult</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.MultImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getMult()
   * @generated
   */
  int MULT = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Mult</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.DivImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getDiv()
   * @generated
   */
  int DIV = 29;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.MathNumberImpl <em>Math Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.MathNumberImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getMathNumber()
   * @generated
   */
  int MATH_NUMBER = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_NUMBER__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Math Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATH_NUMBER_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see dsl.greenhouse.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Model#getHardwareSetup <em>Hardware Setup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hardware Setup</em>'.
   * @see dsl.greenhouse.Model#getHardwareSetup()
   * @see #getModel()
   * @generated
   */
  EReference getModel_HardwareSetup();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Model#getGreenhouses <em>Greenhouses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Greenhouses</em>'.
   * @see dsl.greenhouse.Model#getGreenhouses()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Greenhouses();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.HardwareSetup <em>Hardware Setup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hardware Setup</em>'.
   * @see dsl.greenhouse.HardwareSetup
   * @generated
   */
  EClass getHardwareSetup();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.HardwareSetup#getHardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hardware</em>'.
   * @see dsl.greenhouse.HardwareSetup#getHardware()
   * @see #getHardwareSetup()
   * @generated
   */
  EReference getHardwareSetup_Hardware();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.HardwareSetup#getControllers <em>Controllers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Controllers</em>'.
   * @see dsl.greenhouse.HardwareSetup#getControllers()
   * @see #getHardwareSetup()
   * @generated
   */
  EReference getHardwareSetup_Controllers();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Hardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hardware</em>'.
   * @see dsl.greenhouse.Hardware
   * @generated
   */
  EClass getHardware();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Hardware#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Hardware#getName()
   * @see #getHardware()
   * @generated
   */
  EAttribute getHardware_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingActuator <em>Setting Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Actuator</em>'.
   * @see dsl.greenhouse.SettingActuator
   * @generated
   */
  EClass getSettingActuator();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.SettingActuator#getSettingAction <em>Setting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Setting Action</em>'.
   * @see dsl.greenhouse.SettingActuator#getSettingAction()
   * @see #getSettingActuator()
   * @generated
   */
  EReference getSettingActuator_SettingAction();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingSensor <em>Setting Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Sensor</em>'.
   * @see dsl.greenhouse.SettingSensor
   * @generated
   */
  EClass getSettingSensor();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.SettingSensor#getReducer <em>Reducer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reducer</em>'.
   * @see dsl.greenhouse.SettingSensor#getReducer()
   * @see #getSettingSensor()
   * @generated
   */
  EReference getSettingSensor_Reducer();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.SettingSensor#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Frequency</em>'.
   * @see dsl.greenhouse.SettingSensor#getFrequency()
   * @see #getSettingSensor()
   * @generated
   */
  EReference getSettingSensor_Frequency();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Controller <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Controller</em>'.
   * @see dsl.greenhouse.Controller
   * @generated
   */
  EClass getController();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Controller#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Controller#getName()
   * @see #getController()
   * @generated
   */
  EAttribute getController_Name();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Controller#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see dsl.greenhouse.Controller#getType()
   * @see #getController()
   * @generated
   */
  EReference getController_Type();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Controller#getHeartBeat <em>Heart Beat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Heart Beat</em>'.
   * @see dsl.greenhouse.Controller#getHeartBeat()
   * @see #getController()
   * @generated
   */
  EReference getController_HeartBeat();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Heartbeat <em>Heartbeat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Heartbeat</em>'.
   * @see dsl.greenhouse.Heartbeat
   * @generated
   */
  EClass getHeartbeat();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Heartbeat#getFreq <em>Freq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Freq</em>'.
   * @see dsl.greenhouse.Heartbeat#getFreq()
   * @see #getHeartbeat()
   * @generated
   */
  EReference getHeartbeat_Freq();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.ControllerType <em>Controller Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Controller Type</em>'.
   * @see dsl.greenhouse.ControllerType
   * @generated
   */
  EClass getControllerType();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.ControllerType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.ControllerType#getName()
   * @see #getControllerType()
   * @generated
   */
  EAttribute getControllerType_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Reducer <em>Reducer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reducer</em>'.
   * @see dsl.greenhouse.Reducer
   * @generated
   */
  EClass getReducer();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Reducer#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Reducer#getName()
   * @see #getReducer()
   * @generated
   */
  EAttribute getReducer_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Frequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Frequency</em>'.
   * @see dsl.greenhouse.Frequency
   * @generated
   */
  EClass getFrequency();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Frequency#getFreq <em>Freq</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Freq</em>'.
   * @see dsl.greenhouse.Frequency#getFreq()
   * @see #getFrequency()
   * @generated
   */
  EReference getFrequency_Freq();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Frequency#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see dsl.greenhouse.Frequency#getUnit()
   * @see #getFrequency()
   * @generated
   */
  EAttribute getFrequency_Unit();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingAction <em>Setting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Action</em>'.
   * @see dsl.greenhouse.SettingAction
   * @generated
   */
  EClass getSettingAction();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.SettingAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.SettingAction#getName()
   * @see #getSettingAction()
   * @generated
   */
  EAttribute getSettingAction_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Greenhouse <em>Greenhouse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greenhouse</em>'.
   * @see dsl.greenhouse.Greenhouse
   * @generated
   */
  EClass getGreenhouse();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Greenhouse#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Greenhouse#getName()
   * @see #getGreenhouse()
   * @generated
   */
  EAttribute getGreenhouse_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Greenhouse#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Row</em>'.
   * @see dsl.greenhouse.Greenhouse#getRow()
   * @see #getGreenhouse()
   * @generated
   */
  EReference getGreenhouse_Row();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Greenhouse#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see dsl.greenhouse.Greenhouse#getElements()
   * @see #getGreenhouse()
   * @generated
   */
  EReference getGreenhouse_Elements();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see dsl.greenhouse.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Row#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Row#getName()
   * @see #getRow()
   * @generated
   */
  EAttribute getRow_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Row#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see dsl.greenhouse.Row#getElements()
   * @see #getRow()
   * @generated
   */
  EReference getRow_Elements();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see dsl.greenhouse.GreenhouseElement
   * @generated
   */
  EClass getGreenhouseElement();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowElement <em>Row Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Element</em>'.
   * @see dsl.greenhouse.RowElement
   * @generated
   */
  EClass getRowElement();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator</em>'.
   * @see dsl.greenhouse.GreenhouseActuator
   * @generated
   */
  EClass getGreenhouseActuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseActuator#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getType()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EReference getGreenhouseActuator_Type();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.GreenhouseActuator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getName()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EAttribute getGreenhouseActuator_Name();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseActuator#getController <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Controller</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getController()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EReference getGreenhouseActuator_Controller();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.GreenhouseActuator#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getAction()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EReference getGreenhouseActuator_Action();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseActuator#getSafeState <em>Safe State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Safe State</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getSafeState()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EReference getGreenhouseActuator_SafeState();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowActuator <em>Row Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Actuator</em>'.
   * @see dsl.greenhouse.RowActuator
   * @generated
   */
  EClass getRowActuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowActuator#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see dsl.greenhouse.RowActuator#getType()
   * @see #getRowActuator()
   * @generated
   */
  EReference getRowActuator_Type();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.RowActuator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.RowActuator#getName()
   * @see #getRowActuator()
   * @generated
   */
  EAttribute getRowActuator_Name();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowActuator#getController <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Controller</em>'.
   * @see dsl.greenhouse.RowActuator#getController()
   * @see #getRowActuator()
   * @generated
   */
  EReference getRowActuator_Controller();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.RowActuator#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see dsl.greenhouse.RowActuator#getAction()
   * @see #getRowActuator()
   * @generated
   */
  EReference getRowActuator_Action();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowActuator#getSafeState <em>Safe State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Safe State</em>'.
   * @see dsl.greenhouse.RowActuator#getSafeState()
   * @see #getRowActuator()
   * @generated
   */
  EReference getRowActuator_SafeState();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see dsl.greenhouse.GreenhouseSensor
   * @generated
   */
  EClass getGreenhouseSensor();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseSensor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getType()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EReference getGreenhouseSensor_Type();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.GreenhouseSensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getName()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EAttribute getGreenhouseSensor_Name();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseSensor#getController <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Controller</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getController()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EReference getGreenhouseSensor_Controller();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.GreenhouseSensor#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getVariable()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EReference getGreenhouseSensor_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.GreenhouseSensor#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getStates()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EReference getGreenhouseSensor_States();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowSensor <em>Row Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Sensor</em>'.
   * @see dsl.greenhouse.RowSensor
   * @generated
   */
  EClass getRowSensor();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowSensor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see dsl.greenhouse.RowSensor#getType()
   * @see #getRowSensor()
   * @generated
   */
  EReference getRowSensor_Type();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.RowSensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.RowSensor#getName()
   * @see #getRowSensor()
   * @generated
   */
  EAttribute getRowSensor_Name();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowSensor#getController <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Controller</em>'.
   * @see dsl.greenhouse.RowSensor#getController()
   * @see #getRowSensor()
   * @generated
   */
  EReference getRowSensor_Controller();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.RowSensor#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see dsl.greenhouse.RowSensor#getVariable()
   * @see #getRowSensor()
   * @generated
   */
  EReference getRowSensor_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.RowSensor#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see dsl.greenhouse.RowSensor#getStates()
   * @see #getRowSensor()
   * @generated
   */
  EReference getRowSensor_States();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see dsl.greenhouse.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.State#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see dsl.greenhouse.State#getVariable()
   * @see #getState()
   * @generated
   */
  EReference getState_Variable();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.State#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see dsl.greenhouse.State#getOp()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Op();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.State#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Threshold</em>'.
   * @see dsl.greenhouse.State#getThreshold()
   * @see #getState()
   * @generated
   */
  EReference getState_Threshold();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see dsl.greenhouse.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see dsl.greenhouse.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.Action#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Value</em>'.
   * @see dsl.greenhouse.Action#getValue()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Value();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Action#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Trigger</em>'.
   * @see dsl.greenhouse.Action#getTrigger()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Trigger();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see dsl.greenhouse.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Trigger#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Trigger#getName()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowRuleSet <em>Row Rule Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Rule Set</em>'.
   * @see dsl.greenhouse.RowRuleSet
   * @generated
   */
  EClass getRowRuleSet();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actuator</em>'.
   * @see dsl.greenhouse.RowRuleSet#getActuator()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_Actuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Trigger</em>'.
   * @see dsl.greenhouse.RowRuleSet#getTrigger()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_Trigger();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see dsl.greenhouse.RowRuleSet#getSensor()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_Sensor();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see dsl.greenhouse.RowRuleSet#getState()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_State();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseRuleSet <em>Rule Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Set</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet
   * @generated
   */
  EClass getGreenhouseRuleSet();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actuator</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getActuator()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_Actuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Trigger</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getTrigger()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_Trigger();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getSensor()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_Sensor();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getState()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_State();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see dsl.greenhouse.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see dsl.greenhouse.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dsl.greenhouse.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dsl.greenhouse.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see dsl.greenhouse.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dsl.greenhouse.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dsl.greenhouse.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Mult <em>Mult</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mult</em>'.
   * @see dsl.greenhouse.Mult
   * @generated
   */
  EClass getMult();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Mult#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dsl.greenhouse.Mult#getLeft()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Left();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Mult#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dsl.greenhouse.Mult#getRight()
   * @see #getMult()
   * @generated
   */
  EReference getMult_Right();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see dsl.greenhouse.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Div#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dsl.greenhouse.Div#getLeft()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Left();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Div#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dsl.greenhouse.Div#getRight()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Right();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.MathNumber <em>Math Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Math Number</em>'.
   * @see dsl.greenhouse.MathNumber
   * @generated
   */
  EClass getMathNumber();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.MathNumber#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dsl.greenhouse.MathNumber#getValue()
   * @see #getMathNumber()
   * @generated
   */
  EAttribute getMathNumber_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GreenhouseFactory getGreenhouseFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ModelImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Hardware Setup</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__HARDWARE_SETUP = eINSTANCE.getModel_HardwareSetup();

    /**
     * The meta object literal for the '<em><b>Greenhouses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GREENHOUSES = eINSTANCE.getModel_Greenhouses();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.HardwareSetupImpl <em>Hardware Setup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.HardwareSetupImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardwareSetup()
     * @generated
     */
    EClass HARDWARE_SETUP = eINSTANCE.getHardwareSetup();

    /**
     * The meta object literal for the '<em><b>Hardware</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HARDWARE_SETUP__HARDWARE = eINSTANCE.getHardwareSetup_Hardware();

    /**
     * The meta object literal for the '<em><b>Controllers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HARDWARE_SETUP__CONTROLLERS = eINSTANCE.getHardwareSetup_Controllers();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.HardwareImpl <em>Hardware</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.HardwareImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardware()
     * @generated
     */
    EClass HARDWARE = eINSTANCE.getHardware();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HARDWARE__NAME = eINSTANCE.getHardware_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingActuatorImpl <em>Setting Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingActuatorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingActuator()
     * @generated
     */
    EClass SETTING_ACTUATOR = eINSTANCE.getSettingActuator();

    /**
     * The meta object literal for the '<em><b>Setting Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING_ACTUATOR__SETTING_ACTION = eINSTANCE.getSettingActuator_SettingAction();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingSensorImpl <em>Setting Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingSensorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingSensor()
     * @generated
     */
    EClass SETTING_SENSOR = eINSTANCE.getSettingSensor();

    /**
     * The meta object literal for the '<em><b>Reducer</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING_SENSOR__REDUCER = eINSTANCE.getSettingSensor_Reducer();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING_SENSOR__FREQUENCY = eINSTANCE.getSettingSensor_Frequency();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ControllerImpl <em>Controller</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ControllerImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getController()
     * @generated
     */
    EClass CONTROLLER = eINSTANCE.getController();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROLLER__NAME = eINSTANCE.getController_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROLLER__TYPE = eINSTANCE.getController_Type();

    /**
     * The meta object literal for the '<em><b>Heart Beat</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTROLLER__HEART_BEAT = eINSTANCE.getController_HeartBeat();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.HeartbeatImpl <em>Heartbeat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.HeartbeatImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHeartbeat()
     * @generated
     */
    EClass HEARTBEAT = eINSTANCE.getHeartbeat();

    /**
     * The meta object literal for the '<em><b>Freq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEARTBEAT__FREQ = eINSTANCE.getHeartbeat_Freq();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ControllerTypeImpl <em>Controller Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ControllerTypeImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getControllerType()
     * @generated
     */
    EClass CONTROLLER_TYPE = eINSTANCE.getControllerType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROLLER_TYPE__NAME = eINSTANCE.getControllerType_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ReducerImpl <em>Reducer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ReducerImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getReducer()
     * @generated
     */
    EClass REDUCER = eINSTANCE.getReducer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REDUCER__NAME = eINSTANCE.getReducer_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.FrequencyImpl <em>Frequency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.FrequencyImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getFrequency()
     * @generated
     */
    EClass FREQUENCY = eINSTANCE.getFrequency();

    /**
     * The meta object literal for the '<em><b>Freq</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FREQUENCY__FREQ = eINSTANCE.getFrequency_Freq();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FREQUENCY__UNIT = eINSTANCE.getFrequency_Unit();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingActionImpl <em>Setting Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingActionImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingAction()
     * @generated
     */
    EClass SETTING_ACTION = eINSTANCE.getSettingAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SETTING_ACTION__NAME = eINSTANCE.getSettingAction_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseImpl <em>Greenhouse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouse()
     * @generated
     */
    EClass GREENHOUSE = eINSTANCE.getGreenhouse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREENHOUSE__NAME = eINSTANCE.getGreenhouse_Name();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE__ROW = eINSTANCE.getGreenhouse_Row();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE__ELEMENTS = eINSTANCE.getGreenhouse_Elements();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW__NAME = eINSTANCE.getRow_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__ELEMENTS = eINSTANCE.getRow_Elements();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseElementImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseElement()
     * @generated
     */
    EClass GREENHOUSE_ELEMENT = eINSTANCE.getGreenhouseElement();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowElementImpl <em>Row Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowElementImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowElement()
     * @generated
     */
    EClass ROW_ELEMENT = eINSTANCE.getRowElement();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseActuatorImpl <em>Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseActuatorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseActuator()
     * @generated
     */
    EClass GREENHOUSE_ACTUATOR = eINSTANCE.getGreenhouseActuator();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_ACTUATOR__TYPE = eINSTANCE.getGreenhouseActuator_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREENHOUSE_ACTUATOR__NAME = eINSTANCE.getGreenhouseActuator_Name();

    /**
     * The meta object literal for the '<em><b>Controller</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_ACTUATOR__CONTROLLER = eINSTANCE.getGreenhouseActuator_Controller();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_ACTUATOR__ACTION = eINSTANCE.getGreenhouseActuator_Action();

    /**
     * The meta object literal for the '<em><b>Safe State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_ACTUATOR__SAFE_STATE = eINSTANCE.getGreenhouseActuator_SafeState();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowActuatorImpl <em>Row Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowActuatorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowActuator()
     * @generated
     */
    EClass ROW_ACTUATOR = eINSTANCE.getRowActuator();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_ACTUATOR__TYPE = eINSTANCE.getRowActuator_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_ACTUATOR__NAME = eINSTANCE.getRowActuator_Name();

    /**
     * The meta object literal for the '<em><b>Controller</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_ACTUATOR__CONTROLLER = eINSTANCE.getRowActuator_Controller();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_ACTUATOR__ACTION = eINSTANCE.getRowActuator_Action();

    /**
     * The meta object literal for the '<em><b>Safe State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_ACTUATOR__SAFE_STATE = eINSTANCE.getRowActuator_SafeState();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseSensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseSensorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseSensor()
     * @generated
     */
    EClass GREENHOUSE_SENSOR = eINSTANCE.getGreenhouseSensor();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_SENSOR__TYPE = eINSTANCE.getGreenhouseSensor_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREENHOUSE_SENSOR__NAME = eINSTANCE.getGreenhouseSensor_Name();

    /**
     * The meta object literal for the '<em><b>Controller</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_SENSOR__CONTROLLER = eINSTANCE.getGreenhouseSensor_Controller();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_SENSOR__VARIABLE = eINSTANCE.getGreenhouseSensor_Variable();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_SENSOR__STATES = eINSTANCE.getGreenhouseSensor_States();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowSensorImpl <em>Row Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowSensorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowSensor()
     * @generated
     */
    EClass ROW_SENSOR = eINSTANCE.getRowSensor();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SENSOR__TYPE = eINSTANCE.getRowSensor_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_SENSOR__NAME = eINSTANCE.getRowSensor_Name();

    /**
     * The meta object literal for the '<em><b>Controller</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SENSOR__CONTROLLER = eINSTANCE.getRowSensor_Controller();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SENSOR__VARIABLE = eINSTANCE.getRowSensor_Variable();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SENSOR__STATES = eINSTANCE.getRowSensor_States();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.StateImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__VARIABLE = eINSTANCE.getState_Variable();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__OP = eINSTANCE.getState_Op();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__THRESHOLD = eINSTANCE.getState_Threshold();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.VariableImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ActionImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__VALUE = eINSTANCE.getAction_Value();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__TRIGGER = eINSTANCE.getAction_Trigger();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.TriggerImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__NAME = eINSTANCE.getTrigger_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowRuleSetImpl <em>Row Rule Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowRuleSetImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowRuleSet()
     * @generated
     */
    EClass ROW_RULE_SET = eINSTANCE.getRowRuleSet();

    /**
     * The meta object literal for the '<em><b>Actuator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__ACTUATOR = eINSTANCE.getRowRuleSet_Actuator();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__TRIGGER = eINSTANCE.getRowRuleSet_Trigger();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__SENSOR = eINSTANCE.getRowRuleSet_Sensor();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__STATE = eINSTANCE.getRowRuleSet_State();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseRuleSetImpl <em>Rule Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseRuleSetImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseRuleSet()
     * @generated
     */
    EClass GREENHOUSE_RULE_SET = eINSTANCE.getGreenhouseRuleSet();

    /**
     * The meta object literal for the '<em><b>Actuator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__ACTUATOR = eINSTANCE.getGreenhouseRuleSet_Actuator();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__TRIGGER = eINSTANCE.getGreenhouseRuleSet_Trigger();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__SENSOR = eINSTANCE.getGreenhouseRuleSet_Sensor();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__STATE = eINSTANCE.getGreenhouseRuleSet_State();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ExpressionImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.PlusImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.MinusImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.MultImpl <em>Mult</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.MultImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getMult()
     * @generated
     */
    EClass MULT = eINSTANCE.getMult();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__LEFT = eINSTANCE.getMult_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULT__RIGHT = eINSTANCE.getMult_Right();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.DivImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__LEFT = eINSTANCE.getDiv_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__RIGHT = eINSTANCE.getDiv_Right();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.MathNumberImpl <em>Math Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.MathNumberImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getMathNumber()
     * @generated
     */
    EClass MATH_NUMBER = eINSTANCE.getMathNumber();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATH_NUMBER__VALUE = eINSTANCE.getMathNumber_Value();

  }

} //GreenhousePackage
