/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dsl.greenhouse.GreenhousePackage#getGreenhouseElement()
 * @model
 * @generated
 */
public interface GreenhouseElement extends EObject
{
} // GreenhouseElement
