/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.RowSensor#getType <em>Type</em>}</li>
 *   <li>{@link dsl.greenhouse.RowSensor#getName <em>Name</em>}</li>
 *   <li>{@link dsl.greenhouse.RowSensor#getController <em>Controller</em>}</li>
 *   <li>{@link dsl.greenhouse.RowSensor#getVariable <em>Variable</em>}</li>
 *   <li>{@link dsl.greenhouse.RowSensor#getStates <em>States</em>}</li>
 * </ul>
 *
 * @see dsl.greenhouse.GreenhousePackage#getRowSensor()
 * @model
 * @generated
 */
public interface RowSensor extends RowElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(SettingSensor)
   * @see dsl.greenhouse.GreenhousePackage#getRowSensor_Type()
   * @model
   * @generated
   */
  SettingSensor getType();

  /**
   * Sets the value of the '{@link dsl.greenhouse.RowSensor#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(SettingSensor value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dsl.greenhouse.GreenhousePackage#getRowSensor_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dsl.greenhouse.RowSensor#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Controller</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controller</em>' reference.
   * @see #setController(Controller)
   * @see dsl.greenhouse.GreenhousePackage#getRowSensor_Controller()
   * @model
   * @generated
   */
  Controller getController();

  /**
   * Sets the value of the '{@link dsl.greenhouse.RowSensor#getController <em>Controller</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Controller</em>' reference.
   * @see #getController()
   * @generated
   */
  void setController(Controller value);

  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(Variable)
   * @see dsl.greenhouse.GreenhousePackage#getRowSensor_Variable()
   * @model containment="true"
   * @generated
   */
  Variable getVariable();

  /**
   * Sets the value of the '{@link dsl.greenhouse.RowSensor#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(Variable value);

  /**
   * Returns the value of the '<em><b>States</b></em>' containment reference list.
   * The list contents are of type {@link dsl.greenhouse.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>States</em>' containment reference list.
   * @see dsl.greenhouse.GreenhousePackage#getRowSensor_States()
   * @model containment="true"
   * @generated
   */
  EList<State> getStates();

} // RowSensor
