/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse.impl;

import dsl.greenhouse.Action;
import dsl.greenhouse.Controller;
import dsl.greenhouse.GreenhouseActuator;
import dsl.greenhouse.GreenhousePackage;
import dsl.greenhouse.SettingAction;
import dsl.greenhouse.SettingActuator;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Actuator</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.impl.GreenhouseActuatorImpl#getType <em>Type</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.GreenhouseActuatorImpl#getName <em>Name</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.GreenhouseActuatorImpl#getController <em>Controller</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.GreenhouseActuatorImpl#getAction <em>Action</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.GreenhouseActuatorImpl#getSafeState <em>Safe State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GreenhouseActuatorImpl extends GreenhouseElementImpl implements GreenhouseActuator
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected SettingActuator type;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getController() <em>Controller</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getController()
   * @generated
   * @ordered
   */
  protected Controller controller;

  /**
   * The cached value of the '{@link #getAction() <em>Action</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected EList<Action> action;

  /**
   * The cached value of the '{@link #getSafeState() <em>Safe State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSafeState()
   * @generated
   * @ordered
   */
  protected SettingAction safeState;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreenhouseActuatorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreenhousePackage.Literals.GREENHOUSE_ACTUATOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SettingActuator getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (SettingActuator)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GreenhousePackage.GREENHOUSE_ACTUATOR__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SettingActuator basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(SettingActuator newType)
  {
    SettingActuator oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreenhousePackage.GREENHOUSE_ACTUATOR__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreenhousePackage.GREENHOUSE_ACTUATOR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Controller getController()
  {
    if (controller != null && controller.eIsProxy())
    {
      InternalEObject oldController = (InternalEObject)controller;
      controller = (Controller)eResolveProxy(oldController);
      if (controller != oldController)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GreenhousePackage.GREENHOUSE_ACTUATOR__CONTROLLER, oldController, controller));
      }
    }
    return controller;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Controller basicGetController()
  {
    return controller;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setController(Controller newController)
  {
    Controller oldController = controller;
    controller = newController;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreenhousePackage.GREENHOUSE_ACTUATOR__CONTROLLER, oldController, controller));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Action> getAction()
  {
    if (action == null)
    {
      action = new EObjectContainmentEList<Action>(Action.class, this, GreenhousePackage.GREENHOUSE_ACTUATOR__ACTION);
    }
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SettingAction getSafeState()
  {
    if (safeState != null && safeState.eIsProxy())
    {
      InternalEObject oldSafeState = (InternalEObject)safeState;
      safeState = (SettingAction)eResolveProxy(oldSafeState);
      if (safeState != oldSafeState)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GreenhousePackage.GREENHOUSE_ACTUATOR__SAFE_STATE, oldSafeState, safeState));
      }
    }
    return safeState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SettingAction basicGetSafeState()
  {
    return safeState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSafeState(SettingAction newSafeState)
  {
    SettingAction oldSafeState = safeState;
    safeState = newSafeState;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreenhousePackage.GREENHOUSE_ACTUATOR__SAFE_STATE, oldSafeState, safeState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreenhousePackage.GREENHOUSE_ACTUATOR__ACTION:
        return ((InternalEList<?>)getAction()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreenhousePackage.GREENHOUSE_ACTUATOR__TYPE:
        if (resolve) return getType();
        return basicGetType();
      case GreenhousePackage.GREENHOUSE_ACTUATOR__NAME:
        return getName();
      case GreenhousePackage.GREENHOUSE_ACTUATOR__CONTROLLER:
        if (resolve) return getController();
        return basicGetController();
      case GreenhousePackage.GREENHOUSE_ACTUATOR__ACTION:
        return getAction();
      case GreenhousePackage.GREENHOUSE_ACTUATOR__SAFE_STATE:
        if (resolve) return getSafeState();
        return basicGetSafeState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreenhousePackage.GREENHOUSE_ACTUATOR__TYPE:
        setType((SettingActuator)newValue);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__NAME:
        setName((String)newValue);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__CONTROLLER:
        setController((Controller)newValue);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__ACTION:
        getAction().clear();
        getAction().addAll((Collection<? extends Action>)newValue);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__SAFE_STATE:
        setSafeState((SettingAction)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreenhousePackage.GREENHOUSE_ACTUATOR__TYPE:
        setType((SettingActuator)null);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__CONTROLLER:
        setController((Controller)null);
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__ACTION:
        getAction().clear();
        return;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__SAFE_STATE:
        setSafeState((SettingAction)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreenhousePackage.GREENHOUSE_ACTUATOR__TYPE:
        return type != null;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GreenhousePackage.GREENHOUSE_ACTUATOR__CONTROLLER:
        return controller != null;
      case GreenhousePackage.GREENHOUSE_ACTUATOR__ACTION:
        return action != null && !action.isEmpty();
      case GreenhousePackage.GREENHOUSE_ACTUATOR__SAFE_STATE:
        return safeState != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //GreenhouseActuatorImpl
