/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse.impl;

import dsl.greenhouse.Controller;
import dsl.greenhouse.GreenhousePackage;
import dsl.greenhouse.Hardware;
import dsl.greenhouse.HardwareSetup;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hardware Setup</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.impl.HardwareSetupImpl#getHardware <em>Hardware</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.HardwareSetupImpl#getControllers <em>Controllers</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HardwareSetupImpl extends MinimalEObjectImpl.Container implements HardwareSetup
{
  /**
   * The cached value of the '{@link #getHardware() <em>Hardware</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHardware()
   * @generated
   * @ordered
   */
  protected EList<Hardware> hardware;

  /**
   * The cached value of the '{@link #getControllers() <em>Controllers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getControllers()
   * @generated
   * @ordered
   */
  protected EList<Controller> controllers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HardwareSetupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreenhousePackage.Literals.HARDWARE_SETUP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Hardware> getHardware()
  {
    if (hardware == null)
    {
      hardware = new EObjectContainmentEList<Hardware>(Hardware.class, this, GreenhousePackage.HARDWARE_SETUP__HARDWARE);
    }
    return hardware;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Controller> getControllers()
  {
    if (controllers == null)
    {
      controllers = new EObjectContainmentEList<Controller>(Controller.class, this, GreenhousePackage.HARDWARE_SETUP__CONTROLLERS);
    }
    return controllers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreenhousePackage.HARDWARE_SETUP__HARDWARE:
        return ((InternalEList<?>)getHardware()).basicRemove(otherEnd, msgs);
      case GreenhousePackage.HARDWARE_SETUP__CONTROLLERS:
        return ((InternalEList<?>)getControllers()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreenhousePackage.HARDWARE_SETUP__HARDWARE:
        return getHardware();
      case GreenhousePackage.HARDWARE_SETUP__CONTROLLERS:
        return getControllers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreenhousePackage.HARDWARE_SETUP__HARDWARE:
        getHardware().clear();
        getHardware().addAll((Collection<? extends Hardware>)newValue);
        return;
      case GreenhousePackage.HARDWARE_SETUP__CONTROLLERS:
        getControllers().clear();
        getControllers().addAll((Collection<? extends Controller>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreenhousePackage.HARDWARE_SETUP__HARDWARE:
        getHardware().clear();
        return;
      case GreenhousePackage.HARDWARE_SETUP__CONTROLLERS:
        getControllers().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreenhousePackage.HARDWARE_SETUP__HARDWARE:
        return hardware != null && !hardware.isEmpty();
      case GreenhousePackage.HARDWARE_SETUP__CONTROLLERS:
        return controllers != null && !controllers.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //HardwareSetupImpl
