/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse.impl;

import dsl.greenhouse.Greenhouse;
import dsl.greenhouse.GreenhousePackage;
import dsl.greenhouse.HardwareSetup;
import dsl.greenhouse.Model;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.impl.ModelImpl#getName <em>Name</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.ModelImpl#getHardwareSetup <em>Hardware Setup</em>}</li>
 *   <li>{@link dsl.greenhouse.impl.ModelImpl#getGreenhouses <em>Greenhouses</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getHardwareSetup() <em>Hardware Setup</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHardwareSetup()
   * @generated
   * @ordered
   */
  protected EList<HardwareSetup> hardwareSetup;

  /**
   * The cached value of the '{@link #getGreenhouses() <em>Greenhouses</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGreenhouses()
   * @generated
   * @ordered
   */
  protected EList<Greenhouse> greenhouses;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreenhousePackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GreenhousePackage.MODEL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<HardwareSetup> getHardwareSetup()
  {
    if (hardwareSetup == null)
    {
      hardwareSetup = new EObjectContainmentEList<HardwareSetup>(HardwareSetup.class, this, GreenhousePackage.MODEL__HARDWARE_SETUP);
    }
    return hardwareSetup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Greenhouse> getGreenhouses()
  {
    if (greenhouses == null)
    {
      greenhouses = new EObjectContainmentEList<Greenhouse>(Greenhouse.class, this, GreenhousePackage.MODEL__GREENHOUSES);
    }
    return greenhouses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GreenhousePackage.MODEL__HARDWARE_SETUP:
        return ((InternalEList<?>)getHardwareSetup()).basicRemove(otherEnd, msgs);
      case GreenhousePackage.MODEL__GREENHOUSES:
        return ((InternalEList<?>)getGreenhouses()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GreenhousePackage.MODEL__NAME:
        return getName();
      case GreenhousePackage.MODEL__HARDWARE_SETUP:
        return getHardwareSetup();
      case GreenhousePackage.MODEL__GREENHOUSES:
        return getGreenhouses();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GreenhousePackage.MODEL__NAME:
        setName((String)newValue);
        return;
      case GreenhousePackage.MODEL__HARDWARE_SETUP:
        getHardwareSetup().clear();
        getHardwareSetup().addAll((Collection<? extends HardwareSetup>)newValue);
        return;
      case GreenhousePackage.MODEL__GREENHOUSES:
        getGreenhouses().clear();
        getGreenhouses().addAll((Collection<? extends Greenhouse>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GreenhousePackage.MODEL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GreenhousePackage.MODEL__HARDWARE_SETUP:
        getHardwareSetup().clear();
        return;
      case GreenhousePackage.MODEL__GREENHOUSES:
        getGreenhouses().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GreenhousePackage.MODEL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GreenhousePackage.MODEL__HARDWARE_SETUP:
        return hardwareSetup != null && !hardwareSetup.isEmpty();
      case GreenhousePackage.MODEL__GREENHOUSES:
        return greenhouses != null && !greenhouses.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ModelImpl
