/*
 * generated by Xtext 2.25.0
 */
package dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dsl.GreenhouseRuntimeModule;
import dsl.GreenhouseStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GreenhouseIdeSetup extends GreenhouseStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GreenhouseRuntimeModule(), new GreenhouseIdeModule()));
	}
	
}
