/**
 * generated by Xtext 2.25.0
 */
package dsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GreenhouseIdeModule extends AbstractGreenhouseIdeModule {
}
