/*
 * generated by Xtext 2.25.0
 */
package dsl.parser.antlr;

import com.google.inject.Inject;
import dsl.parser.antlr.internal.InternalGreenhouseParser;
import dsl.services.GreenhouseGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GreenhouseParser extends AbstractAntlrParser {

	@Inject
	private GreenhouseGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGreenhouseParser createParser(XtextTokenStream stream) {
		return new InternalGreenhouseParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public GreenhouseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GreenhouseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
