/*
 * generated by Xtext 2.25.0
 */
package dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dsl.ide.contentassist.antlr.internal.InternalGreenhouseParser;
import dsl.services.GreenhouseGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GreenhouseParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GreenhouseGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GreenhouseGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getHardwareAccess().getAlternatives(), "rule__Hardware__Alternatives");
			builder.put(grammarAccess.getControllerTypeAccess().getNameAlternatives_0(), "rule__ControllerType__NameAlternatives_0");
			builder.put(grammarAccess.getReducerAccess().getNameAlternatives_0(), "rule__Reducer__NameAlternatives_0");
			builder.put(grammarAccess.getFrequencyAccess().getUnitAlternatives_3_0(), "rule__Frequency__UnitAlternatives_3_0");
			builder.put(grammarAccess.getGreenhouseElementAccess().getAlternatives(), "rule__GreenhouseElement__Alternatives");
			builder.put(grammarAccess.getRowElementAccess().getAlternatives(), "rule__RowElement__Alternatives");
			builder.put(grammarAccess.getStateAccess().getOpAlternatives_3_0(), "rule__State__OpAlternatives_3_0");
			builder.put(grammarAccess.getExpAccess().getAlternatives_1_0(), "rule__Exp__Alternatives_1_0");
			builder.put(grammarAccess.getFactorAccess().getAlternatives_1_0(), "rule__Factor__Alternatives_1_0");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getHardwareSetupAccess().getGroup(), "rule__HardwareSetup__Group__0");
			builder.put(grammarAccess.getSettingActuatorAccess().getGroup(), "rule__SettingActuator__Group__0");
			builder.put(grammarAccess.getSettingActuatorAccess().getGroup_5(), "rule__SettingActuator__Group_5__0");
			builder.put(grammarAccess.getSettingSensorAccess().getGroup(), "rule__SettingSensor__Group__0");
			builder.put(grammarAccess.getControllerAccess().getGroup(), "rule__Controller__Group__0");
			builder.put(grammarAccess.getHeartbeatAccess().getGroup(), "rule__Heartbeat__Group__0");
			builder.put(grammarAccess.getFrequencyAccess().getGroup(), "rule__Frequency__Group__0");
			builder.put(grammarAccess.getGreenhouseAccess().getGroup(), "rule__Greenhouse__Group__0");
			builder.put(grammarAccess.getRowAccess().getGroup(), "rule__Row__Group__0");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getGroup(), "rule__GreenhouseActuator__Group__0");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getGroup_6(), "rule__GreenhouseActuator__Group_6__0");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getGroup_7(), "rule__GreenhouseActuator__Group_7__0");
			builder.put(grammarAccess.getRowActuatorAccess().getGroup(), "rule__RowActuator__Group__0");
			builder.put(grammarAccess.getRowActuatorAccess().getGroup_5(), "rule__RowActuator__Group_5__0");
			builder.put(grammarAccess.getRowActuatorAccess().getGroup_6(), "rule__RowActuator__Group_6__0");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getGroup(), "rule__GreenhouseSensor__Group__0");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getGroup_11(), "rule__GreenhouseSensor__Group_11__0");
			builder.put(grammarAccess.getRowSensorAccess().getGroup(), "rule__RowSensor__Group__0");
			builder.put(grammarAccess.getRowSensorAccess().getGroup_10(), "rule__RowSensor__Group_10__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup(), "rule__Trigger__Group__0");
			builder.put(grammarAccess.getRowRuleSetAccess().getGroup(), "rule__RowRuleSet__Group__0");
			builder.put(grammarAccess.getGreenhouseRuleSetAccess().getGroup(), "rule__GreenhouseRuleSet__Group__0");
			builder.put(grammarAccess.getExpAccess().getGroup(), "rule__Exp__Group__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1(), "rule__Exp__Group_1__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1_0_0(), "rule__Exp__Group_1_0_0__0");
			builder.put(grammarAccess.getExpAccess().getGroup_1_0_1(), "rule__Exp__Group_1_0_1__0");
			builder.put(grammarAccess.getFactorAccess().getGroup(), "rule__Factor__Group__0");
			builder.put(grammarAccess.getFactorAccess().getGroup_1(), "rule__Factor__Group_1__0");
			builder.put(grammarAccess.getFactorAccess().getGroup_1_0_0(), "rule__Factor__Group_1_0_0__0");
			builder.put(grammarAccess.getFactorAccess().getGroup_1_0_1(), "rule__Factor__Group_1_0_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_1(), "rule__Primary__Group_1__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_1(), "rule__Model__NameAssignment_1");
			builder.put(grammarAccess.getModelAccess().getHardwareSetupAssignment_2(), "rule__Model__HardwareSetupAssignment_2");
			builder.put(grammarAccess.getModelAccess().getGreenhousesAssignment_3(), "rule__Model__GreenhousesAssignment_3");
			builder.put(grammarAccess.getHardwareSetupAccess().getHardwareAssignment_3(), "rule__HardwareSetup__HardwareAssignment_3");
			builder.put(grammarAccess.getHardwareSetupAccess().getControllersAssignment_5(), "rule__HardwareSetup__ControllersAssignment_5");
			builder.put(grammarAccess.getSettingActuatorAccess().getNameAssignment_1(), "rule__SettingActuator__NameAssignment_1");
			builder.put(grammarAccess.getSettingActuatorAccess().getSettingActionAssignment_4(), "rule__SettingActuator__SettingActionAssignment_4");
			builder.put(grammarAccess.getSettingActuatorAccess().getSettingActionAssignment_5_1(), "rule__SettingActuator__SettingActionAssignment_5_1");
			builder.put(grammarAccess.getSettingSensorAccess().getNameAssignment_1(), "rule__SettingSensor__NameAssignment_1");
			builder.put(grammarAccess.getSettingSensorAccess().getReducerAssignment_3(), "rule__SettingSensor__ReducerAssignment_3");
			builder.put(grammarAccess.getSettingSensorAccess().getFrequencyAssignment_4(), "rule__SettingSensor__FrequencyAssignment_4");
			builder.put(grammarAccess.getControllerAccess().getNameAssignment_1(), "rule__Controller__NameAssignment_1");
			builder.put(grammarAccess.getControllerAccess().getTypeAssignment_4(), "rule__Controller__TypeAssignment_4");
			builder.put(grammarAccess.getControllerAccess().getHeartBeatAssignment_6(), "rule__Controller__HeartBeatAssignment_6");
			builder.put(grammarAccess.getHeartbeatAccess().getFreqAssignment_2(), "rule__Heartbeat__FreqAssignment_2");
			builder.put(grammarAccess.getControllerTypeAccess().getNameAssignment(), "rule__ControllerType__NameAssignment");
			builder.put(grammarAccess.getReducerAccess().getNameAssignment(), "rule__Reducer__NameAssignment");
			builder.put(grammarAccess.getFrequencyAccess().getFreqAssignment_0(), "rule__Frequency__FreqAssignment_0");
			builder.put(grammarAccess.getFrequencyAccess().getUnitAssignment_3(), "rule__Frequency__UnitAssignment_3");
			builder.put(grammarAccess.getSettingActionAccess().getNameAssignment(), "rule__SettingAction__NameAssignment");
			builder.put(grammarAccess.getGreenhouseAccess().getNameAssignment_1(), "rule__Greenhouse__NameAssignment_1");
			builder.put(grammarAccess.getGreenhouseAccess().getRowAssignment_2(), "rule__Greenhouse__RowAssignment_2");
			builder.put(grammarAccess.getGreenhouseAccess().getElementsAssignment_3(), "rule__Greenhouse__ElementsAssignment_3");
			builder.put(grammarAccess.getRowAccess().getNameAssignment_1(), "rule__Row__NameAssignment_1");
			builder.put(grammarAccess.getRowAccess().getElementsAssignment_3(), "rule__Row__ElementsAssignment_3");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getTypeAssignment_1(), "rule__GreenhouseActuator__TypeAssignment_1");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getNameAssignment_2(), "rule__GreenhouseActuator__NameAssignment_2");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getControllerAssignment_5(), "rule__GreenhouseActuator__ControllerAssignment_5");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getActionAssignment_6_1(), "rule__GreenhouseActuator__ActionAssignment_6_1");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getActionAssignment_7_2(), "rule__GreenhouseActuator__ActionAssignment_7_2");
			builder.put(grammarAccess.getGreenhouseActuatorAccess().getSafeStateAssignment_12(), "rule__GreenhouseActuator__SafeStateAssignment_12");
			builder.put(grammarAccess.getRowActuatorAccess().getTypeAssignment_0(), "rule__RowActuator__TypeAssignment_0");
			builder.put(grammarAccess.getRowActuatorAccess().getNameAssignment_1(), "rule__RowActuator__NameAssignment_1");
			builder.put(grammarAccess.getRowActuatorAccess().getControllerAssignment_4(), "rule__RowActuator__ControllerAssignment_4");
			builder.put(grammarAccess.getRowActuatorAccess().getActionAssignment_5_1(), "rule__RowActuator__ActionAssignment_5_1");
			builder.put(grammarAccess.getRowActuatorAccess().getActionAssignment_6_2(), "rule__RowActuator__ActionAssignment_6_2");
			builder.put(grammarAccess.getRowActuatorAccess().getSafeStateAssignment_11(), "rule__RowActuator__SafeStateAssignment_11");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getTypeAssignment_1(), "rule__GreenhouseSensor__TypeAssignment_1");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getNameAssignment_2(), "rule__GreenhouseSensor__NameAssignment_2");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getControllerAssignment_5(), "rule__GreenhouseSensor__ControllerAssignment_5");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getVariableAssignment_7(), "rule__GreenhouseSensor__VariableAssignment_7");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getStatesAssignment_10(), "rule__GreenhouseSensor__StatesAssignment_10");
			builder.put(grammarAccess.getGreenhouseSensorAccess().getStatesAssignment_11_1(), "rule__GreenhouseSensor__StatesAssignment_11_1");
			builder.put(grammarAccess.getRowSensorAccess().getTypeAssignment_0(), "rule__RowSensor__TypeAssignment_0");
			builder.put(grammarAccess.getRowSensorAccess().getNameAssignment_1(), "rule__RowSensor__NameAssignment_1");
			builder.put(grammarAccess.getRowSensorAccess().getControllerAssignment_4(), "rule__RowSensor__ControllerAssignment_4");
			builder.put(grammarAccess.getRowSensorAccess().getVariableAssignment_6(), "rule__RowSensor__VariableAssignment_6");
			builder.put(grammarAccess.getRowSensorAccess().getStatesAssignment_9(), "rule__RowSensor__StatesAssignment_9");
			builder.put(grammarAccess.getRowSensorAccess().getStatesAssignment_10_1(), "rule__RowSensor__StatesAssignment_10_1");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_0(), "rule__State__NameAssignment_0");
			builder.put(grammarAccess.getStateAccess().getVariableAssignment_2(), "rule__State__VariableAssignment_2");
			builder.put(grammarAccess.getStateAccess().getOpAssignment_3(), "rule__State__OpAssignment_3");
			builder.put(grammarAccess.getStateAccess().getThresholdAssignment_4(), "rule__State__ThresholdAssignment_4");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1(), "rule__Variable__NameAssignment_1");
			builder.put(grammarAccess.getActionAccess().getValueAssignment_0(), "rule__Action__ValueAssignment_0");
			builder.put(grammarAccess.getActionAccess().getTriggerAssignment_3(), "rule__Action__TriggerAssignment_3");
			builder.put(grammarAccess.getTriggerAccess().getNameAssignment_1(), "rule__Trigger__NameAssignment_1");
			builder.put(grammarAccess.getRowRuleSetAccess().getActuatorAssignment_2(), "rule__RowRuleSet__ActuatorAssignment_2");
			builder.put(grammarAccess.getRowRuleSetAccess().getTriggerAssignment_4(), "rule__RowRuleSet__TriggerAssignment_4");
			builder.put(grammarAccess.getRowRuleSetAccess().getSensorAssignment_6(), "rule__RowRuleSet__SensorAssignment_6");
			builder.put(grammarAccess.getRowRuleSetAccess().getStateAssignment_8(), "rule__RowRuleSet__StateAssignment_8");
			builder.put(grammarAccess.getGreenhouseRuleSetAccess().getActuatorAssignment_3(), "rule__GreenhouseRuleSet__ActuatorAssignment_3");
			builder.put(grammarAccess.getGreenhouseRuleSetAccess().getTriggerAssignment_5(), "rule__GreenhouseRuleSet__TriggerAssignment_5");
			builder.put(grammarAccess.getGreenhouseRuleSetAccess().getSensorAssignment_7(), "rule__GreenhouseRuleSet__SensorAssignment_7");
			builder.put(grammarAccess.getGreenhouseRuleSetAccess().getStateAssignment_9(), "rule__GreenhouseRuleSet__StateAssignment_9");
			builder.put(grammarAccess.getExpAccess().getRightAssignment_1_1(), "rule__Exp__RightAssignment_1_1");
			builder.put(grammarAccess.getFactorAccess().getRightAssignment_1_1(), "rule__Factor__RightAssignment_1_1");
			builder.put(grammarAccess.getPrimaryAccess().getValueAssignment_0_1(), "rule__Primary__ValueAssignment_0_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GreenhouseGrammarAccess grammarAccess;

	@Override
	protected InternalGreenhouseParser createParser() {
		InternalGreenhouseParser result = new InternalGreenhouseParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GreenhouseGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GreenhouseGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
